#!/usr/bin/php
<?php
include_once __DIR__.DIRECTORY_SEPARATOR."cli-script-helper-functions.php";

if( !isPhpRunningInCliMode() ) {

    echo 'Error: This script should only be run via the command line!!';
    
} else {

    try {
        
        createController($argc, $argv);

    } catch(\Exception $e) {

        $msg = 'Exception was thrown in ' . $e->getFile() . ' on line ' . $e->getLine()
            . PHP_EOL . $e->getMessage()
            . PHP_EOL . 'Exception Trace:' . PHP_EOL . $e->getTraceAsString()
            . PHP_EOL . PHP_EOL . 'Please submit a bug report to https://github.com/rotexsoft/slim-skeleton-mvc-tools/issues if symptoms persist.' . PHP_EOL;

        printError($msg);
    }
}

