#!/usr/bin/php
<?php
include_once __DIR__.DIRECTORY_SEPARATOR."cli-script-helper-functions.php";

if( !\SlimMvcTools\Functions\CliHelpers\isPhpRunningInCliMode() ) {

    echo 'Error: This script should only be run via the command line!!';
    exit(\SlimMvcTools\Functions\CliHelpers\CliExitCodes::FAILURE_EXIT);
    
} else {

    try {
        $current_directory = getcwd(); 
        echo "Current working directory: " . getcwd() . PHP_EOL;
        $result = \SlimMvcTools\Functions\CliHelpers\createController($argc, $argv);
        
        \SlimMvcTools\Functions\CliHelpers\printType(
            $result->getReturnCode(), $result->getReturnMessage(), true
        );
        
        if($result->getReturnCode() === \SlimMvcTools\Functions\CliHelpers\CliExitCodes::SUCCESS_EXIT) {
            
            passthru("cd {$current_directory} && composer dump-autoload -o");
        }
        
        exit($result->getReturnCode());

    } catch(\Exception $e) {

        $msg = 'Exception was thrown in ' . $e->getFile() . ' on line ' . $e->getLine() . PHP_EOL . $e->getMessage()
            . PHP_EOL . 'Exception Trace:' . PHP_EOL . $e->getTraceAsString() . PHP_EOL . PHP_EOL 
            . 'Please submit a bug report to https://github.com/rotexsoft/slim-skeleton-mvc-tools/issues if symptoms persist.' . PHP_EOL;

        \SlimMvcTools\Functions\CliHelpers\printError($msg);
        exit(\SlimMvcTools\Functions\CliHelpers\CliExitCodes::EXCEPTION_EXIT);
    }
}
